Scenario Outline: Receive Key Account Information with account with account not in DM
    Given account is not currently in DM
    When account triggered into DM
    Then  the collection manager receives key account and product information "<Account Number>"
   

      Account Number
      "<Payer Indicator>"
      "<Payment Method>"
      "<Current Pay Method>"
      "<Name>"
      "<Accrued Interest>"
      "<Capital outstanding>"
      "<Charge rate>"
      "<Employer code>"
      "<Employer description>"
      "<Date account opened>"
      "<Service Fee>"
      "<Hold code>"
      "<Hold code description>"
      "<Installment>"
      "<Insurance instalment>"
      "<Insurance type>"
      "<Insurer>"
      "<Interest base>"
      "<Interest option>"
      "<Interest period>"
      "<Interest variance>"
      "<Insurance premium date>"
      "<Last payment>"
      "<Loan type>"
      "<Loan type description>"
      "<Loan term>"
      "<Loan grant date>"
      "<Loan debit order amount>"
      "<Months in arrears>"
      "<First instalment date>"
      "<Total balance>"
      "<Months to go>"
      "<Debt item description>"
      "<Next debit order due date>"
      "<Original loan amount>"
      "<PL own insurance indicator and name>"
      "<Collection arrears>"
      "<System arrears>"
      "<Restructure indicator>"
      "<Restructure date>"
      "<Restructure reason>"
      "<Total instalment>"
      "<Term end date>"
      "<The payment profile>"
      "<Banking Information>"
      "<Debit Order Rejection Count>"
      "<NAEDO Rejection Date>"
      "<NAEDO Reject Reason>"
      "<Debit Order Due Date>"
      "<Effective Date>"
      "<Expected Payment Day>"
      "<Funding Bank Account>"
      "<Funding Branch Number>"
      "<Funding Bank>"
      "<Instalment Amount>"
      "<Debit Order Amount>"

      "<Cash payment or EFT payment>"

      "<Standing instructions">
      "<Field flag>"
